const path = require('path'); // used do after get path
const CleanWebpackPlugin = require('clean-webpack-plugin') // to erase files that were renamed

module.exports = {
  entry : ['@babel/polyfill', './app-src/app.js'], // entry is where the index.js/app.js/main.js comes and the polyfill also
  output: {
    filename: 'bundle.js', // name of the file generated by webpack
    path: path.resolve(__dirname, 'dist'), // respolve the path and also can change the name of folder created
  },
  module: {
    rules: [
      {
        test: /\.js$/, // regex to get the files that end with .js
        exclude: /node_modules/, // excluding node_modules to dont loose tiem
        use: {
          loader: 'babel-loader', // use loader to make things happen (he will go in .babelrc config)
        }
      }
    ]
  }
  plugins: [
    new CleanWebpackPlugin(['dist']) // folder to remove files 
  ]
}

